Menubar
danielamoreno699/mobilePortafolioMainPage pull request #15
Opened 2023-03-06 22:01 UTC by danielamoreno699

### Hamburguer icon displaying effect

In this milestone Project, **We**:

-Added visual effect to the hamburguer icon,
-Added additional hidden div container as an overlayout ,
-Added a js file to select the html elements 
-Added  navigation link  to the navbar list

2023-03-06 22:08 UTC, addod19 commented
### Hi @danielamoreno699, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the README file is missing the future features section.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-06 23:01 UTC, tresorsawasawa commented on index.html
> +    </div>
- [ ] Kindly make sure that when the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed. To help you just use the `<a>` tag on each navigation option then use the id the `href` attribute and after refer the used `id` on each section. Remember to also remove one of your nav option lists as you repeated it twice
e.g.
```HTML
    <li class="li-navbartool"><a href="#portfoilo">Portfolio</a></li>
    <li class="li-navbartool"><a href="#about">About</a></li>
    ...
```
**IMPORTANT:** When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed should work for both **Mobile** and **Desktop** versions

2023-03-06 23:04 UTC, tresorsawasawa commented on styles.css
> +  /* background-size: cover; */
- [ ] Kindly ensure that you remove all commented and unused code lines from your code base to make cleaner and for best practices reasons.

2023-03-06 23:09 UTC, tresorsawasawa commented on README.md
- [ ] Kindly ensure that you added all the contributors of the project with working social media links in the `Authors` section of your README and fill all sections with correct content(e.g.: **Show your support**, **Acknowledgments**,...) to make your documentation professional

2023-03-07 03:46 UTC, Shedrack-Sunday requested changes
Hi @danielamoreno699    👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
✅ Proper PR summary 
  
# Required Changes ♻️

- [x] I must admit you have really put in the effort so far in this project, however, the changes required a minor adjustment to fit the previous reviewers suggestions

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-07 03:46 UTC, Shedrack-Sunday commented on README.md
- [ ] As stated by the previous reviewer, you need all files in the linter directory for `HTML-CSS-JS`. Presently you're missing one fro the pic I attached below. Note that these are files to help you stick to best practices 👍 

## View:
![image](https://user-images.githubusercontent.com/50990925/223313641-817b0469-0117-4d0c-8044-be506d5865c3.png)

2023-03-07 03:46 UTC, Shedrack-Sunday commented on main.js
> +
- [ ] Also as suggested by the previous reviewer, kindly ensure that you remove all commented and unused code lines from your code base to make it cleaner and for best practices reasons.

2023-03-07 03:46 UTC, Shedrack-Sunday commented on index.html
> +            <li class="li-navbartool" id="contact">Contact</li>
- [ ] As noted here, please make sure that when the user clicks (or taps) any of the mobile menu options, the correct part of the page is displayed. To help you just use the `<a>` tag on each navigation option then use the id the `href` attribute and refer to the user id on each section. Remember to also remove one of your nav option lists as you repeated it twice
e.g.

    ```
    <li class="li-navbartool"><a href="#portfoilo">Portfolio</a></li>
    <li class="li-navbartool"><a href="#about">About</a></li>
    ```
    
 ## Instructions :
 
![image](https://user-images.githubusercontent.com/50990925/223314959-f0356f5d-81ec-4bd9-8081-e3940f7cbc5f.png)

2023-03-07 03:46 UTC, Shedrack-Sunday commented on README.md
-  [ ] Finally, as suggested by your last reviewer, please complete the sections as pointed out in the image below. These are guidelines to show you how to make our work professional, which is very important:

## View
![image](https://user-images.githubusercontent.com/50990925/223315469-a4ca1158-4d4e-4541-869e-5b70d5f057d7.png)

2023-03-07 15:54 UTC, Davidosky007 requested changes
Hi @danielamoreno699 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 15:54 UTC, Davidosky007 commented on index.html
> +            <li class="li-navbartool"> <a href="#contact" class="li-navbartool">Contact</a></li>
* Well done working on the changes requested so far 👏 but one required change is still left undone
* when a user clicks on the menu options the mobile menu should disappear **HINT** you could add a conditional statement to hide the drop-down
![image](https://user-images.githubusercontent.com/52497246/223474327-f56eb314-9700-4e69-a018-9b912ad268cf.png)
 

https://user-images.githubusercontent.com/52497246/223475191-198a73ab-c0c9-4aea-8800-726adbca9a41.mp4

2023-03-07 16:46 UTC, Zuhaib042 approved these changes
Hi @danielamoreno699 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approve](https://media.giphy.com/media/bdaMVCP6bPIVWc0B3g/giphy.gif)

## Highlights
✅ Good Implementation of suggested changes
✅ Professional PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 03:44 UTC, merged