Cards
danielamoreno699/mobilePortafolioMainPage pull request #2
Opened 2023-02-17 17:22 UTC by danielamoreno699

### Cards for mobile portafolio project

In this milestone  **Cards for mobile portafolio project, I**:
- Created required linter dependecies
- Created the HTML file
- Created the CSS file
- Incorporated the images in Assets folder
- Modified the MIT.md file to LICENSE.md
- Modified the README file

2023-02-17 18:19 UTC, ouasamine requested changes
Hi @danielamoreno699  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
- You paid close attention to design details well done 👏🏽 ✔️ 
- Your code is well organised and clean ✔️ 
- Your commit messages are descriptive clear nice jobe 👍🏽 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 18:19 UTC, ouasamine commented on src/index.html
> +<!--here starts section personal description-->
- [ ] You need to work on spacing here as well to match the Figma design and you also need to work and the top right corner of your description section and make it rounded like the Figma template, please check the images below 🔽 

### Figma Design
![figma 2](https://user-images.githubusercontent.com/104319462/219742088-f34dacb1-b76a-4d84-960b-eb06f1188206.png)

### Your Design

![student 2](https://user-images.githubusercontent.com/104319462/219742114-f9a2e33a-9ffa-410a-9cbc-07bf88ef32f6.png)

2023-02-17 18:19 UTC, ouasamine commented on src/index.html
> +        <ul class="social-media">
- [ ] Please put this header "LETS CONNECT" in `<hx>` tag instead of `<p>` as it's more semantically correct.

2023-02-17 18:19 UTC, ouasamine commented on src/index.html
> +             <li>
- [ ] Nice work bulding this skills section 👏🏽 however, according to the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md) "languages" should be insid a `<li>` tag instead of `<p>` 🔽 
> Please use ul and li for categories in "About myself" section. Languages, Frameworks, and Skills should be list items.

2023-02-17 18:19 UTC, ouasamine commented on src/index.html
> +                     <p>CSS</p>
- [ ] The list of the technologies looks great, but to respect the HTML semantics we need to put these technologies inside `<li>` tags as well 🔽 
> Please use ul and li for categories in "Work" section. Html, Css, and Javascript should be list items.

2023-02-17 18:24 UTC, ouasamine commented
- [ ] One more thing @danielamoreno699 , please try to make your PR title more verbose, something like "Add cards and description section" instead of just "cards" you can go back and edit it, good luck 👍🏽

2023-02-17 22:00 UTC, divinecharlotte commented on src/index.html
> +        </div>
- [ ] Good job implementing the works section, however, you still need to work on the right side cards spacing  to match the Figma as shown below 🔽 , remember that according to the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md) you need to stick to the Fiigma template as much as possible.
- your design 👇 
![yd](https://user-images.githubusercontent.com/60146030/219801743-4181c74d-3a3e-4596-a31d-bc1a43290ad5.PNG)
- Figma design 👇 

![fi](https://user-images.githubusercontent.com/60146030/219801871-9fd9a252-c77e-46f9-8036-0d12c281d436.PNG)

2023-02-18 02:20 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @danielamoreno699 ,

I am Favour 👩🏽 , your reviewer for this PR.

Great Job implementing all the required changes suggested by the previous reviewer. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 03:15 UTC, merged