Web version
danielamoreno699/mobilePortafolioMainPage pull request #6
Opened 2023-02-23 22:55 UTC by danielamoreno699

### **web version portafolio project**

**In this milestone of project, I:**
-Added some additional classes to the css
-Added the media queries for Desktop version 
-Made some changes to the html elements

2023-02-23 23:05 UTC, Alfredbis29 reviewed
Hi @danielamoreno699  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linters error , kindly fix this then ask for another :wink: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-24 04:51 UTC, didierganthier requested changes
Hi @danielamoreno699 ,

🎉 Good job so far! You're making great progress on this project, but there are still a few areas that need attention before we can move on to the next step.

<img src="https://media.giphy.com/media/3oEduMcvxTNPlGuhH2/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-02-24 04:51 UTC, didierganthier commented on src/index.html
> +        <div class="card card4">
Good work on starting with the Desktop version 🖥️  but the cards, especially this one, are breaking when resizing 📏 consider fixing this to improve the UI. This is what you have so far 👇🏽 

![Screenshot 2023-02-23 at 22 52 09](https://user-images.githubusercontent.com/45739963/221088558-4180e516-b2f6-4daa-93d9-f3c4cbd568b8.png)

The space is not properly attributed and the "See project" button is going outside of the card. 👀

2023-02-24 04:51 UTC, didierganthier commented on src/index.html
>      <div class="card-container">
The card section shows a lot of hard work 💪🏽 I can see that but let's see how we can improve it, your cards are not using the width properly. See below 👇🏽 

## Figma
![Screenshot 2023-02-23 at 23 20 15](https://user-images.githubusercontent.com/45739963/221090927-1e1d895c-3cf4-4a8c-80e1-2f3c92f24ae0.png)

## Your design
![Screenshot 2023-02-23 at 22 50 30](https://user-images.githubusercontent.com/45739963/221090860-154624c7-00d0-41a1-8a8f-20cc7cbecbe0.png)

This issue appears when I go below `768px` and when I get to `375px` it shows also a disproportion in the margin here (same issue for the whole page), this issue is due to some `overflow` issue. See below 👇🏽 
![Screenshot 2023-02-23 at 23 22 27](https://user-images.githubusercontent.com/45739963/221091144-a4d0eae2-71fd-446d-b05b-babe4adc1a9b.png)

2023-02-24 04:51 UTC, didierganthier commented on src/styles.css
> +  .contact-form {
Good job once again 💯 but something is not quite right with the contact form here, your elements are overflowing the container on the mobile version. See below 👇🏽 

![Screenshot 2023-02-23 at 22 51 09](https://user-images.githubusercontent.com/45739963/221091653-f6672d04-6fe7-43e4-8025-a819b80a37ee.png)

And there's an extra margin below the container here that's not part of the design for the Desktop version

![Screenshot 2023-02-23 at 22 52 36](https://user-images.githubusercontent.com/45739963/221091744-9a253b30-455d-40c1-8eca-f082c7d9d9ea.png)

Also, make sure that the space here is attributed properly and that the elements are centered. See the Figma 👇🏽 
![Screenshot 2023-02-23 at 23 29 15](https://user-images.githubusercontent.com/45739963/221091920-dd22be83-663a-4470-95c3-7d2e0b0eb71c.png)

2023-02-24 04:51 UTC, didierganthier commented on src/index.html
> +<section class="personal-description">
Nice About section 😉 but the style of the header goes away when I resize the screen and I get just below `768px` kindly try to address that as it is really essential that the whole page is responsive, see below 👇🏽 

## Figma
![Screenshot 2023-02-23 at 23 32 56](https://user-images.githubusercontent.com/45739963/221092332-5bb7eca2-0efe-4102-9433-fb00775f7398.png)


## Your design
![Screenshot 2023-02-23 at 23 31 23](https://user-images.githubusercontent.com/45739963/221092153-3bbf1678-d41c-4818-84ca-f3a17dd8175d.png)

Also make sure that the space is used properly 👍🏽

2023-02-24 04:51 UTC, didierganthier commented on src/index.html
> + <div class="container-languages">
Nice set of languages 🤯 👩🏽‍💻 but let's see how we can improve this more. It kinda breaks when I resize just below `768px`, try to fix that and your project will look better.

![Screenshot 2023-02-23 at 23 35 46](https://user-images.githubusercontent.com/45739963/221092684-52297a76-92ae-4208-a2d8-86af590ad62f.png)

2023-02-24 04:51 UTC, didierganthier commented on src/index.html
> +        </ul>
Love the hamburger icon 😄 but this is not quite right, the hamburger should be fully on the right and the space should be properly attributed, the fonts also need some work to match the **Figma** make sure to adjust yours to fit the design more. See below 👇🏽 

## Figma
![Screenshot 2023-02-23 at 23 40 55](https://user-images.githubusercontent.com/45739963/221093402-807632b6-dcd1-42de-bd03-d475dd316a88.png)


## Your design
![Screenshot 2023-02-23 at 23 37 50](https://user-images.githubusercontent.com/45739963/221092974-6ea0f8bc-5342-42ce-bb4b-4488e4b1e619.png)

2023-02-24 04:51 UTC, didierganthier commented on src/index.html
> +    </div>
Nice button 👍🏽 but it lacks the `Hover effect` on both mobile and Desktop. See below 👇🏽 

![Screenshot 2023-02-23 at 23 46 22](https://user-images.githubusercontent.com/45739963/221094061-acb8c58e-2e4b-464b-9d86-d5e82cae6292.png)

2023-02-25 17:16 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @danielamoreno699, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions
- You have improved a lot in your design. Though there are few more things to be improved. You should take some time and look at the Figma Design and improve your Portfolio.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 17:16 UTC, RaoAkif commented on src/index.html
>              </li>
[OPTIONAL] Since you have improved a lot in your design. Though there are few more things to be improved. You should take some time and look at the Figma Design and improve your Portfolio.

| Your Design   | FIGMA Design  |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61361037/221370444-cc0baef2-c089-4354-9642-a98254c3f5e9.png)| ![image](https://user-images.githubusercontent.com/61361037/221370495-2f8e9dfb-e4fa-4c0b-8e7f-7105559c991b.png)|

2023-02-25 17:24 UTC, merged